// Generates src/lib/icons.ts — the pixelarticons the site actually uses, inlined.
//
// @iconify/react resolves unknown icon names by calling api.iconify.design at runtime, which
// means a third-party request on every page load and icons that pop in after paint. Every
// icon name in this codebase is a literal string, so they can all be found by scanning and
// baked into the bundle instead. Names that slip past the scan still fall back to the API,
// so a miss degrades rather than breaks.
//
// Runs automatically before `npm run build`; run `npm run icons` to refresh it by hand.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const PREFIX = 'pixelarticons'

function sourceFiles(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) return sourceFiles(path)
    return /\.tsx?$/.test(entry) ? [path] : []
  })
}

const used = new Set()
for (const file of sourceFiles(join(root, 'src'))) {
  for (const m of readFileSync(file, 'utf8').matchAll(new RegExp(`${PREFIX}:([a-z0-9-]+)`, 'g'))) {
    used.add(m[1])
  }
}

const set = JSON.parse(readFileSync(join(root, 'node_modules', `@iconify-json/${PREFIX}`, 'icons.json'), 'utf8'))

const icons = {}
const missing = []
for (const name of [...used].sort()) {
  // An alias points at another icon in the set rather than carrying its own body.
  const resolved = set.icons[name] ?? set.icons[set.aliases?.[name]?.parent]
  if (resolved) icons[name] = resolved
  else missing.push(name)
}

if (missing.length) console.warn(`build-icons: not in the ${PREFIX} set, will fall back to the API: ${missing.join(', ')}`)

const out = `// GENERATED by scripts/build-icons.mjs — do not edit. Run \`npm run icons\` to refresh.
// Registers the ${Object.keys(icons).length} pixelarticons this site uses, so @iconify/react renders them
// from the bundle instead of fetching them from api.iconify.design at runtime.
import { addCollection } from '@iconify/react'

addCollection(${JSON.stringify({ prefix: set.prefix, width: set.width, height: set.height, icons }, null, 2)})
`

writeFileSync(join(root, 'src', 'lib', 'icons.ts'), out)
console.log(`build-icons: inlined ${Object.keys(icons).length} icons (${(out.length / 1024).toFixed(1)} kB)`)
