// GENERATED by scripts/build-icons.mjs — do not edit. Run `npm run icons` to refresh.
// Registers the 42 pixelarticons this site uses, so @iconify/react renders them
// from the bundle instead of fetching them from api.iconify.design at runtime.
import { addCollection } from '@iconify/react'

addCollection({
  "prefix": "pixelarticons",
  "width": 24,
  "height": 24,
  "icons": {
    "arrow-left": {
      "body": "<g fill=\"currentColor\"><path d=\"M20 11v2H4v-2zM8 13v2H6v-2zm2 2v2H8v-2zm2 2v2h-2v-2zm-4-6V9H6v2z\"/><path d=\"M10 15V7H8v8zm2 2V5h-2v12z\"/></g>"
    },
    "arrow-right": {
      "body": "<g fill=\"currentColor\"><path d=\"M4 11v2h16v-2zm12 2v2h2v-2zm-2 2v2h2v-2zm-2 2v2h2v-2zm4-6V9h2v2z\"/><path d=\"M14 15V7h2v8zm-2 2V5h2v12z\"/></g>"
    },
    "arrow-up": {
      "body": "<g fill=\"currentColor\"><path d=\"M11 20h2V4h-2zm2-12h2V6h-2zm2 2h2V8h-2zm2 2h2v-2h-2zm-6-4H9V6h2z\"/><path d=\"M15 10H7V8h8zm2 2H5v-2h12z\"/></g>"
    },
    "briefcase": {
      "body": "<path fill=\"currentColor\" d=\"M2 8h2v12H2zm18 0h2v12h-2zM4 6h16v2H4zm0 14h16v2H4zM8 4h2v2H8zm2-2h4v2h-4zm4 2h2v2h-2z\"/>"
    },
    "camera": {
      "body": "<path fill=\"currentColor\" d=\"M4 5h4v2H4zm4-2h8v2H8zm8 2h4v2h-4zM2 7h2v12H2zm2 12h16v2H4zM20 7h2v12h-2zM10 8h4v2h-4zm0 6h4v2h-4zm-2-4h2v4H8zm6 0h2v4h-2z\"/>"
    },
    "check-double": {
      "body": "<path fill=\"currentColor\" d=\"M7 18H5v-2h2zm6 0h-2v-2h2zm-8-2H3v-2h2zm4 0H7v-2h2zm6-2v2h-2v-2zM3 14H1v-2h2zm8 0H9v-2h2zm6 0h-2v-2h2zm-4-2h-2v-2h2zm6 0h-2v-2h2zm-4-2h-2V8h2zm6 0h-2V8h2zm-4-2h-2V6h2zm6 0h-2V6h2z\"/>"
    },
    "checkbox-on": {
      "body": "<path fill=\"currentColor\" d=\"M4 2h16v2H4zm0 18h16v2H4zM2 4h2v16H2zm18 0h2v16h-2zM7 12h2v2H7zm2 2h2v2H9zm2-2h2v2h-2zm2-2h2v2h-2zm2-2h2v2h-2z\"/>"
    },
    "chevron-down": {
      "body": "<path fill=\"currentColor\" d=\"M13 16h-2v-2h2zm-2-2H9v-2h2zm4 0h-2v-2h2zm-6-2H7v-2h2zm8 0h-2v-2h2zM7 10H5V8h2zm12 0h-2V8h2z\"/>"
    },
    "chevron-left": {
      "body": "<path fill=\"currentColor\" d=\"M8 13v-2h2v2zm2-2V9h2v2zm0 4v-2h2v2zm2-6V7h2v2zm0 8v-2h2v2zm2-10V5h2v2zm0 12v-2h2v2z\"/>"
    },
    "chevron-right": {
      "body": "<path fill=\"currentColor\" d=\"M16 13v-2h-2v2zm-2-2V9h-2v2zm0 4v-2h-2v2zm-2-6V7h-2v2zm0 8v-2h-2v2zM10 7V5H8v2zm0 12v-2H8v2z\"/>"
    },
    "code": {
      "body": "<path fill=\"currentColor\" d=\"M8 5h2v2H8zM6 7h2v2H6zM4 9h2v2H4zm-2 2h2v2H2zm2 2h2v2H4zm2 2h2v2H6zm2 2h2v2H8zm8-12h-2v2h2zm2 2h-2v2h2zm2 2h-2v2h2zm2 2h-2v2h2zm-2 2h-2v2h2zm-2 2h-2v2h2zm-2 2h-2v2h2z\"/>"
    },
    "contact": {
      "body": "<path fill=\"currentColor\" d=\"M2 2h20v2H2zM0 4h2v16H0zm22 0h2v16h-2zM2 20h20v2H2zM14 7h6v2h-6zm0 4h6v2h-6zm0 4h4v2h-4zM6 7h4v4H6zm0 6h4v2H6zm4 2h2v2h-2zm-6 0h2v2H4z\"/>"
    },
    "crown": {
      "body": "<g fill=\"currentColor\"><path d=\"M3 3h2v12H3zm16 0h2v12h-2zm-8 0h2v2h-2zM9 5h2v2H9zM5 5h2v2H5z\"/><path d=\"M3 3h2v2H3zm4 4h2v2H7zm6-2h2v2h-2zm2 2h2v2h-2zm2-2h2v2h-2zM5 15h14v2H5zm-2 4h18v2H3z\"/></g>"
    },
    "diamond-gem": {
      "body": "<path fill=\"currentColor\" d=\"M7 1h10v2H7zM5 3h2v2H5zm12 0h2v2h-2zm2 2h2v2h-2zm0 8h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zm-2-2h2v2H9zm-2-2h2v2H7zm-2-2h2v2H5zm-2-2h2v2H3zm0-8h2v2H3zM1 7h2v6H1zm20 0h2v6h-2zM3 9h18v2H3zm6-6h2v3H9zM7 6h2v3H7zm8 0h2v3h-2zm-8 5h2v2H7zm2 2h2v3H9zm2 3h2v3h-2zm2-3h2v3h-2zm2-2h2v2h-2zm-2-8h2v3h-2z\"/>"
    },
    "download": {
      "body": "<g fill=\"currentColor\"><path d=\"M21 15v4h-2v-4zm-2 4v2H5v-2zM5 15v4H3v-4zm8-12v14h-2V3z\"/><path d=\"M7 11v2h10v-2zm2 2v2h2v-2zm4 0v2h2v-2z\"/><path d=\"M15 11v2h2v-2z\"/></g>"
    },
    "external-link": {
      "body": "<g fill=\"currentColor\"><path d=\"M11 5H5v2h6zM5 7H3v12h2zm12 12H5v2h12zm2-6h-2v6h2zm-8 0H9v2h2zm2-2h-2v2h2zm2-2h-2v2h2zm2-2h-2v2h2zm2-2h-2v2h2zm2-2h-2v8h2z\"/><path d=\"M21 3h-8v2h8z\"/></g>"
    },
    "file": {
      "body": "<g fill=\"currentColor\"><path d=\"M6 4H4v16h2zm10-2H6v2h10zm4 4h-2v14h2zm-2 14H6v2h12zM16 4h2v2h-2zm-4 0h2v6h-2z\"/><path d=\"M12 8h6v2h-6z\"/></g>"
    },
    "fire": {
      "body": "<g fill=\"currentColor\"><path d=\"M9 2h2v4H9zM7 6h2v2H7zM5 8h2v2H5zm8 2h2v2h-2zm2-2h2v2h-2zm2 2h2v2h-2zm2 2h2v6h-2zM3 10h2v8H3zm8-4h2v4h-2zm6 12h2v2h-2zM7 20h10v2H7zm-2-2h2v2H5zm4-2h6v4H9z\"/><path d=\"M11 14h2v3h-2z\"/></g>"
    },
    "flag": {
      "body": "<g fill=\"currentColor\"><path d=\"M4 2h2v20H4z\"/><path d=\"M4 4h16v2H4zm12 2h2v2h-2zm-2 2h2v2h-2zm2 2h2v2h-2zM4 12h16v2H4z\"/></g>"
    },
    "gamepad": {
      "body": "<g fill=\"currentColor\"><path d=\"M4 4h16v2H4zm0 14h16v2H4zM2 6h2v12H2zm18 0h2v12h-2zM8 9h2v6H8z\"/><path d=\"M6 11h6v2H6zm8-2h2v2h-2zm2 4h2v2h-2z\"/></g>"
    },
    "github": {
      "body": "<path fill=\"currentColor\" d=\"M5 2h4v2H7v2H5zm0 10H3V6h2zm2 2H5v-2h2zm2 2v-2H7v2H3v-2H1v2h2v2h4v4h2v-4h2v-2zm0 0v2H7v-2zm6-12v2H9V4zm4 2h-2V4h-2V2h4zm0 6V6h2v6zm-2 2v-2h2v2zm-2 2v-2h2v2zm0 2h-2v-2h2zm0 0h2v4h-2z\"/>",
      "hidden": true
    },
    "hand": {
      "body": "<path fill=\"currentColor\" d=\"M21 7h2v5h-2zm-4-2h2v7h-2zm-4-2h2v8h-2zM9 3h2v8H9zM5 5h2v8H5zm14 0h2v2h-2zm-4-2h2v2h-2zm-4-2h2v2h-2zM7 3h2v2H7zm-4 8h2v2H3zm-2 2h2v2H1zm0 2h2v2H1zm2 2h2v2H3zm2 2h2v2H5zm2 2h12v2H7zm12-2h2v2h-2zm2-7h2v7h-2zM5 13h2v2H5zm2 2h2v2H7z\"/>"
    },
    "heart": {
      "body": "<path fill=\"currentColor\" d=\"M13 22h-2v-2h2zm-2-2H9v-2h2zm4 0h-2v-2h2zm-6-2H7v-2h2zm8 0h-2v-2h2zM7 16H5v-2h2zm12 0h-2v-2h2zM5 14H3v-2h2zm16 0h-2v-2h2zM3 12H1V6h2zm20 0h-2V6h2zM13 8h-2V6h2zM5 6H3V4h2zm6 0H9V4h2zm4 0h-2V4h2zm6 0h-2V4h2zM9 4H5V2h4zm10 0h-4V2h4z\"/>"
    },
    "list": {
      "body": "<path fill=\"currentColor\" d=\"M6 6H4v2h2zm14 0H8v2h12zM4 11h2v2H4zm16 0H8v2h12zM4 16h2v2H4zm16 0H8v2h12z\"/>",
      "hidden": true
    },
    "lock": {
      "body": "<path fill=\"currentColor\" d=\"M5 8h14v2H5zm0 12h14v2H5zM3 10h2v10H3zm16 0h2v10h-2zM7 4h2v4H7zm2-2h6v2H9zm6 2h2v4h-2z\"/>"
    },
    "mail": {
      "body": "<path fill=\"currentColor\" d=\"M6 8h2v2H6zm2 2h2v2H8zm10-2h-2v2h2zm-2 2h-2v2h2zm-6 2h4v2h-4zM2 6h2v12H2zm18 0h2v12h-2zM4 4h16v2H4zm0 14h16v2H4z\"/>"
    },
    "map": {
      "body": "<path fill=\"currentColor\" d=\"M8 2h2v2h2v2h-2v10H8V6H6V4h2zM4 8V6h2v2zm2 10v2H4v2H2V8h2v10zm0 0h2v-2H6zm6 0h-2v-2h2zm2-10V6h-2v2zm2 0h-2v10h-2v2h2v2h2v-2h2v-2h2v-2h2V2h-2v2h-2v2h-2zm0 0h2V6h2v10h-2v2h-2z\"/>",
      "hidden": true
    },
    "move": {
      "body": "<path fill=\"currentColor\" d=\"M13 0h-2v2H9v2H7v2h2V4h2v7H4V9h2V7H4v2H2v2H0v2h2v2h2v2h2v-2H4v-2h7v7H9v-2H7v2h2v2h2v2h2v-2h2v-2h2v-2h-2v2h-2v-7h7v2h-2v2h2v-2h2v-2h2v-2h-2V9h-2V7h-2v2h2v2h-7V4h2v2h2V4h-2V2h-2z\"/>",
      "hidden": true
    },
    "music": {
      "body": "<path fill=\"currentColor\" d=\"M4 12h4v2H4zm-2 2h2v4H2zm2 4h4v2H4zM8 6h2v12H8zm10 0h2v12h-2zm-6 8h2v4h-2zm2-2h4v2h-4zm0 6h4v2h-4zM10 4h8v2h-8z\"/>"
    },
    "phone": {
      "body": "<path fill=\"currentColor\" d=\"M4 1h5v2H4zm5 2h2v4H9zM7 7h2v4H7zm-3 5h2v2H4zM2 3h2v9H2zm7 8h2v2H9zm2 2h2v2h-2zm2 2h4v2h-4zm4-2h4v2h-4zm4 2h2v5h-2zM6 14h2v2H6zm2 2h2v2H8zm2 2h2v2h-2zm2 2h9v2h-9z\"/>"
    },
    "play": {
      "body": "<path fill=\"currentColor\" d=\"M15 11h-2V9h2zm0 4h-2v-2h2zm-2 2h-2v-2h2zm0-8h-2V7h2zm-2-2H9V5h2zM9 21H7V3h2zm6-8h2v-2h-2zm-6 4h2v2H9z\"/>"
    },
    "reload": {
      "body": "<g fill=\"currentColor\"><path d=\"M16 4h2v6h-2zm-2-2h2v2h-2zm0 2h2v8h-2zM4 8H2v5h2z\"/><path d=\"M4 6h16v2H4zm4 14H6v-6h2zm2 2H8v-2h2zm0-2H8v-8h2zm10-4h2v-5h-2z\"/><path d=\"M20 18H4v-2h16z\"/></g>"
    },
    "repeat": {
      "body": "<g fill=\"currentColor\"><path d=\"M17 5h2v2h-2zM5 17h2v2H5zm6-14h2v6h-2zM9 1h2v8H9zm0 8h2v2H9zm10 8H9v2h10zM5 7H3v10h2z\"/><path d=\"M13 15h-2v6h2zm2-2h-2v8h2zm0 8h-2v2h2zM5 5h10v2H5zm14 12h2V7h-2z\"/></g>"
    },
    "skull": {
      "body": "<g fill=\"currentColor\"><path d=\"M7 20h2v2H7zm4 0h2v2h-2zm4 0h2v2h-2zm-6-4h2v4H9zm4 0h2v4h-2zm-8-2h2v6H5zm12 0h2v6h-2z\"/><path d=\"M3 14h4v2H3zM1 4h2v10H1zm20 0h2v10h-2zM3 2h18v2H3zm14 12h4v2h-4zM8 7h2v4H8zm6 0h2v4h-2z\"/></g>"
    },
    "sparkles": {
      "body": "<g fill=\"currentColor\"><path d=\"M11 1h2v4h-2zm0 22h2v-4h-2zM9 5h2v4H9zm0 14h2v-4H9zm4-14h2v4h-2zm0 14h2v-4h-2zM5 9h4v2H5zm14 0h-4v2h4zM1 11h4v2H1zm22 0h-4v2h4zM5 13h4v2H5zm14 0h-4v2h4zm0-12h2v6h-2z\"/><path d=\"M17 3h6v2h-6zM3 17h2v2H3zm-2 2h2v2H1zm2 2h2v2H3zm2-2h2v2H5z\"/></g>"
    },
    "speed-fast": {
      "body": "<path fill=\"currentColor\" d=\"M5 19H3v-2h2zm16 0h-2v-2h2zM3 17H1v-6h2zm11 0h-4v-4h4zm9 0h-2v-6h2zm-7-4h-2v-2h2zM5 11H3V9h2zm13 0h-2V9h2zM9 9H5V7h4zm11 0h-2V7h2zm-5-2H9V5h6z\"/>"
    },
    "target": {
      "body": "<path fill=\"currentColor\" d=\"M5 1h14v2H5zM3 3h2v2H3zm0 16h2v2H3zm16 0h2v2h-2zm0-16h2v2h-2zm2 2h2v14h-2zM5 21h14v2H5zM1 5h2v14H1zm8 0h6v2H9zM5 9h2v6H5zm4 8h6v2H9zm8-8h2v6h-2zm-6 0h2v2h-2zM7 7h2v2H7zm0 8h2v2H7zm8 0h2v2h-2zm0-8h2v2h-2zm-6 4h2v2H9zm2 2h2v2h-2zm2-2h2v2h-2z\"/>"
    },
    "trophy": {
      "body": "<path fill=\"currentColor\" d=\"M16 17h-3v2h2v2H9v-2h2v-2H8v-2h8zm2-12h4v6h-2V7h-2v4h2v2h-2v2h-2V5H8v10H6v-2H4v-2h2V7H4v4H2V5h4V3h12z\"/>"
    },
    "volume": {
      "body": "<path fill=\"currentColor\" d=\"M17 22h-2v-2h-2v-2h2V6h-2V4h2V2h2zm-4-4h-2v-2h2zM11 8v2H9v4h2v2H7V8zm2 0h-2V6h2z\"/>"
    },
    "volume-2": {
      "body": "<path fill=\"currentColor\" d=\"M13 22h-2v-2H9v-2h2V6H9V4h2V2h2zm-4-4H7v-2h2zm10 0h-4v-2h4zM7 10H5v4h2v2H3V8h4zm14 6h-2V8h2zm-4-2h-2v-4h2zM9 8H7V6h2zm10 0h-4V6h4z\"/>"
    },
    "zap": {
      "body": "<path fill=\"currentColor\" d=\"M4 13h8v6h2v2h-2v2h-2v-8H2v-4h2zm12 6h-2v-2h2zm2-2h-2v-2h2zm2-2h-2v-2h2zm-6-6h8v4h-2v-2h-8V5h-2V3h2V1h2zm-8 2H4V9h2zm2-2H6V7h2zm2-2H8V5h2z\"/>"
    },
    "zap-off": {
      "body": "<g fill=\"currentColor\"><path d=\"M10 13h2v10h-2z\"/><path d=\"M2 13h10v2H2zM12 1h2v6h-2zm4 8h6v2h-6zm4 2h2v2h-2zm-4 4h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zM2 11h2v2H2zm2-2h2v2H4zm2-2h2v2H6zm4-4h2v2h-2zM2 1h2v2H2zm2 2h2v2H4zm2 2h2v2H6zm2 2h2v2H8zm2 2h2v2h-2zm2 2h2v2h-2zm2 2h2v2h-2z\"/><path d=\"M16 15h2v2h-2zm2 2h2v2h-2zm2 2h2v2h-2z\"/></g>"
    }
  }
})
